# Generated by Django 5.2 on 2025-04-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buszy_app', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_company', models.CharField(max_length=50)),
                ('bus_plate', models.CharField(max_length=10)),
                ('seats_emp', models.IntegerField()),
                ('seats_full', models.IntegerField()),
                ('crew', models.CharField(max_length=100)),
                ('cities', models.JSONField()),
            ],
            options={
                'db_table': 'voyage',
            },
        ),
        migrations.CreateModel(
            name='VoyageListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_company', models.CharField(max_length=50)),
                ('bus_time', models.TimeField()),
                ('bus_list_begin', models.CharField(max_length=20)),
                ('bus_list_end', models.CharField(max_length=20)),
                ('bus_list_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='buszy_app.voyage')),
            ],
            options={
                'db_table': 'voyage_listing',
            },
        ),
    ]
