# Generated by Django 5.2 on 2025-04-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buszy_app', '0003_voyage_voyagelisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='id',
        ),
        migrations.AddField(
            model_name='voyage',
            name='bus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='seats_emp',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='seats_full',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='voyagelisting',
            name='bus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage', to='buszy_app.voyage'),
        ),
    ]
