# Generated by Django 5.2 on 2025-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buszy_app', '0004_remove_voyage_id_voyage_bus_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_comment', models.CharField(max_length=255)),
                ('ticket_id', models.IntegerField()),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=20)),
                ('end_location', models.CharField(max_length=20)),
                ('seat', models.IntegerField()),
                ('seat_status', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('voyage_date', models.DateField()),
                ('voyage_time', models.TimeField()),
                ('seat', models.IntegerField()),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='voyage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voyagelisting',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='individual', max_length=20),
            preserve_default=False,
        ),
    ]
